language: node_js
node_js:
  - "12"
sudo: required
jobs:
  include:
    - stage: test
      script: npm run compile
    - stage: deploy
      script: bash ./scripts/travis-deploy.sh
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
